package main.java.message.UseCase;


import main.java.message.Message_R;
import main.java.order.Order;



/**
 * This class is an UseCase class of the message sent to customer or admin. This kind of message is for the popup
 * feedback of order for customer and the feedback of order for admin when he/she require to see the order details.
 * This class is used for generate message for Customer and Admin.
 * @author GEN LI (Reagan)
 */

public class SendMessageUseCase {

    /**
     * This method is used for the generation of the popup message for Customer when he/she place an order.
     * @param order An Order type variable that represents an order generated by customers.
     * @return Return the content of the message generated for the customers.
     */

    public static Message_R create_message_R(Order order) {
        return new Message_R(order);
    }


}
